version: 4.8.2.{build}
clone_folder: c:\projects\nlogweb
configuration: Release
image: Visual Studio 2017
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '4.0.0'
  assembly_file_version: '{version}' #NLog.Web
  assembly_informational_version: '{version}' #NLog.Web
nuget:
  project_feed: true
matrix:
  fast_finish: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
  
skip_tags: true

install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.7.3/nuget.exe

build_script:
- ps: |
    $versionPrefix = "4.8.2"
    $versionSuffix = ""
    $versionBuild = $versionPrefix + "." + ${env:APPVEYOR_BUILD_NUMBER}
    $versionNuget = $versionPrefix
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
        $versionPrefix = $versionBuild
        $versionSuffix = "PR" + $env:APPVEYOR_PULL_REQUEST_NUMBER
    }
    if ($versionSuffix)
    {
        $versionNuget = $versionPrefix + "-" + $versionSuffix
    }
    $build_aspnet = "build_aspnet.bat", "-nuget_version=$versionNuget"
    & cmd /c $build_aspnet
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    $build_aspnetcore = "build_aspnetcore.bat", "-version_prefix=$versionPrefix", "-version_build=$versionBuild", "-version_suffix=$versionSuffix"
    & cmd /c $build_aspnetcore
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
